### PR TITLE
Fix sequence implementation

### PR DESCRIPTION
**Pull request by vouillon**

### CODE REVIEW

**Comment by jrochel** [comment]
If the implementation of `Dllist` is buggy and/or not perfectly suitable to this package (which I had presumed without the appropriate skepticism), we should maybe rather copy the `Lwt_sequence` module on which the code was based on to begin with. Any objections, @vasilisp, @vouillon ?

**Comment by vasilisp** [comment]
No objection from me. It is only a 226-line module; MIT-licensed, practically no-maintenance and with not much potential for bugs.

**Comment by vouillon** [comment]
The point is that the type of a sequence should be `'a dllist option ref` and not just `'a dllist option`. And then, you have to update the sequence when you add or remove nodes. Otherwise, your sequences are always going to remain empty (equal to `None`).

**Comment by jrochel** [comment]
We decided to go with a copy of `Lwt_sequence`: https://github.com/ocsigen/resource-pooling/commit/cb1c3ad3985ca72141d48bf9cd9f8a2a77988f87

**Pull request closed without merging**
